--------------------------------------------------------
--  Fichier créé - lundi-décembre-28-2020   
--------------------------------------------------------
DROP TABLE "KARMANDI"."AGENTS";
DROP TABLE "KARMANDI"."CLIENTS";
DROP TABLE "KARMANDI"."COMMANDES";
DROP TABLE "KARMANDI"."CONGÉ";
DROP TABLE "KARMANDI"."EMPLACEMENT";
DROP TABLE "KARMANDI"."EMPLOYEE";
DROP TABLE "KARMANDI"."FACTUREE";
DROP TABLE "KARMANDI"."FOURNISSEURS";
DROP TABLE "KARMANDI"."MATERIEL";
DROP TABLE "KARMANDI"."RECETTE";
DROP TABLE "KARMANDI"."RECLAMATION";
DROP TABLE "KARMANDI"."TRANSPORT";
--------------------------------------------------------
--  DDL for Table AGENTS
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."AGENTS" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."CLIENTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDES
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."COMMANDES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM_COMMANDE" VARCHAR2(20 BYTE), 
	"NBC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGÉ
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."CONGÉ" 
   (	"IDP" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" VARCHAR2(20 BYTE), 
	"DUREE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLACEMENT
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."EMPLACEMENT" 
   (	"NOM_SECTEUR" VARCHAR2(20 BYTE), 
	"VILLE" VARCHAR2(20 BYTE), 
	"CODE_POSTAL" VARCHAR2(20 BYTE), 
	"DATE_AJOUT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."EMPLOYEE" 
   (	"IDP" VARCHAR2(4 BYTE) DEFAULT NULL, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTUREE
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."FACTUREE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"DATE_P" VARCHAR2(20 BYTE), 
	"MONTANT" VARCHAR2(20 BYTE), 
	"SOURCE" VARCHAR2(20 BYTE), 
	"MODE_P" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."FOURNISSEURS" 
   (	"NUMERO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."MATERIEL" 
   (	"REFERENCE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECETTE
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."RECETTE" 
   (	"ID_R" VARCHAR2(20 BYTE), 
	"DATE_R" VARCHAR2(20 BYTE), 
	"MONTANT_R" VARCHAR2(20 BYTE), 
	"SOURCE_R" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECLAMATION
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."RECLAMATION" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"SUJET" VARCHAR2(20 BYTE), 
	"COMMENTAIRE" VARCHAR2(20 BYTE), 
	"DATE_RECLAMATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSPORT
--------------------------------------------------------

  CREATE TABLE "KARMANDI"."TRANSPORT" 
   (	"MODELE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MATRICULE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KARMANDI.AGENTS
SET DEFINE OFF;
Insert into KARMANDI.AGENTS (CIN,NOM,PRENOM,MDP) values ('12','admin','admin','admin');
Insert into KARMANDI.AGENTS (CIN,NOM,PRENOM,MDP) values ('150','karmandi','karmandi','123');
REM INSERTING into KARMANDI.CLIENTS
SET DEFINE OFF;
Insert into KARMANDI.CLIENTS (ID,NOM,PRENOM,ADRESSE) values ('155','mhiri','mhiri','ariana');
Insert into KARMANDI.CLIENTS (ID,NOM,PRENOM,ADRESSE) values ('199','oumaima','karmandi','kram');
REM INSERTING into KARMANDI.COMMANDES
SET DEFINE OFF;
Insert into KARMANDI.COMMANDES (ID,NOM_COMMANDE,NBC) values ('155',null,'0');
REM INSERTING into KARMANDI."CONGÉ"
SET DEFINE OFF;
Insert into KARMANDI."CONGÉ" (IDP,NOM,DATE_DEBUT,DUREE) values ('1555','mimo','30/12/2020','4');
Insert into KARMANDI."CONGÉ" (IDP,NOM,DATE_DEBUT,DUREE) values ('1555','mimo','01/01/2000','6');
Insert into KARMANDI."CONGÉ" (IDP,NOM,DATE_DEBUT,DUREE) values ('1222','aziz','27/11/2020','3');
REM INSERTING into KARMANDI.EMPLACEMENT
SET DEFINE OFF;
Insert into KARMANDI.EMPLACEMENT (NOM_SECTEUR,VILLE,CODE_POSTAL,DATE_AJOUT) values ('kram','jhgfd','jhgfds','trez');
Insert into KARMANDI.EMPLACEMENT (NOM_SECTEUR,VILLE,CODE_POSTAL,DATE_AJOUT) values ('marsa','marsa','2014','20/05/2020');
REM INSERTING into KARMANDI.EMPLOYEE
SET DEFINE OFF;
Insert into KARMANDI.EMPLOYEE (IDP,NOM,PRENOM,ADRESS) values ('1555','mimo','mimo','kram');
Insert into KARMANDI.EMPLOYEE (IDP,NOM,PRENOM,ADRESS) values ('1999','oumaima','karmandi','kram');
Insert into KARMANDI.EMPLOYEE (IDP,NOM,PRENOM,ADRESS) values ('1222','aziz','karmandi','tunis');
Insert into KARMANDI.EMPLOYEE (IDP,NOM,PRENOM,ADRESS) values ('5871','fgh','dfg','fgh');
REM INSERTING into KARMANDI.FACTUREE
SET DEFINE OFF;
Insert into KARMANDI.FACTUREE (ID,DATE_P,MONTANT,SOURCE,MODE_P) values ('0','01/12/2020','320','kkkk','Espece');
Insert into KARMANDI.FACTUREE (ID,DATE_P,MONTANT,SOURCE,MODE_P) values ('2','01/12/2020','500','jjjj','Carte bancaire');
Insert into KARMANDI.FACTUREE (ID,DATE_P,MONTANT,SOURCE,MODE_P) values ('25','03/12/2020','600',null,'Carte bancaire');
Insert into KARMANDI.FACTUREE (ID,DATE_P,MONTANT,SOURCE,MODE_P) values ('95','02/12/2020',null,null,'Cheque');
REM INSERTING into KARMANDI.FOURNISSEURS
SET DEFINE OFF;
Insert into KARMANDI.FOURNISSEURS (NUMERO,EMAIL,NOM,ADRESSE,TYPE) values ('250','oumaima','oumaima','kram','Materiaux');
REM INSERTING into KARMANDI.MATERIEL
SET DEFINE OFF;
Insert into KARMANDI.MATERIEL (REFERENCE,TYPE,CODE) values ('1555','bwm','123');
Insert into KARMANDI.MATERIEL (REFERENCE,TYPE,CODE) values ('128','fgh','251');
Insert into KARMANDI.MATERIEL (REFERENCE,TYPE,CODE) values ('250','knbfd','0');
REM INSERTING into KARMANDI.RECETTE
SET DEFINE OFF;
Insert into KARMANDI.RECETTE (ID_R,DATE_R,MONTANT_R,SOURCE_R) values ('1','03/12/2020','700','600');
Insert into KARMANDI.RECETTE (ID_R,DATE_R,MONTANT_R,SOURCE_R) values ('12','03/12/2020','600','200');
REM INSERTING into KARMANDI.RECLAMATION
SET DEFINE OFF;
Insert into KARMANDI.RECLAMATION (CODE,SUJET,COMMENTAIRE,DATE_RECLAMATION) values ('hjglf','manque','kkkk','nbvc');
Insert into KARMANDI.RECLAMATION (CODE,SUJET,COMMENTAIRE,DATE_RECLAMATION) values ('aaa','aaaa','aaa','aaa');
REM INSERTING into KARMANDI.TRANSPORT
SET DEFINE OFF;
Insert into KARMANDI.TRANSPORT (MODELE,TYPE,MATRICULE) values ('fghj','bwm','125');
--------------------------------------------------------
--  DDL for Index AGENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."AGENTS_PK" ON "KARMANDI"."AGENTS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."CLIENTS_PK" ON "KARMANDI"."CLIENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLACEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."EMPLACEMENT_PK" ON "KARMANDI"."EMPLACEMENT" ("NOM_SECTEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."TABLE1_PK" ON "KARMANDI"."EMPLOYEE" ("IDP", "NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTUREE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."FACTUREE_PK" ON "KARMANDI"."FACTUREE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."FOURNISSEURS_PK" ON "KARMANDI"."FOURNISSEURS" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."MATERIEL_PK" ON "KARMANDI"."MATERIEL" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECETTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."RECETTE_PK" ON "KARMANDI"."RECETTE" ("ID_R") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECLAMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."RECLAMATION_PK" ON "KARMANDI"."RECLAMATION" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANSPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KARMANDI"."TRANSPORT_PK" ON "KARMANDI"."TRANSPORT" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AGENTS
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."AGENTS" ADD CONSTRAINT "AGENTS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."AGENTS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."CLIENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."COMMANDES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLACEMENT
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."EMPLACEMENT" ADD CONSTRAINT "EMPLACEMENT_PK" PRIMARY KEY ("NOM_SECTEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."EMPLACEMENT" MODIFY ("NOM_SECTEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."EMPLOYEE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("IDP", "NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."EMPLOYEE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "KARMANDI"."EMPLOYEE" MODIFY ("IDP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTUREE
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."FACTUREE" ADD CONSTRAINT "FACTUREE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."FACTUREE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEURS_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."FOURNISSEURS" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."MATERIEL" ADD CONSTRAINT "MATERIEL_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."MATERIEL" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECETTE
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."RECETTE" ADD CONSTRAINT "RECETTE_PK" PRIMARY KEY ("ID_R")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."RECETTE" MODIFY ("ID_R" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECLAMATION
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."RECLAMATION" ADD CONSTRAINT "RECLAMATION_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."RECLAMATION" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSPORT
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."TRANSPORT" ADD CONSTRAINT "TRANSPORT_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KARMANDI"."TRANSPORT" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDES
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."COMMANDES" ADD CONSTRAINT "COMMANDES_FK1" FOREIGN KEY ("ID")
	  REFERENCES "KARMANDI"."CLIENTS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONGÉ
--------------------------------------------------------

  ALTER TABLE "KARMANDI"."CONGÉ" ADD CONSTRAINT "CONGÉ_FK1" FOREIGN KEY ("IDP", "NOM")
	  REFERENCES "KARMANDI"."EMPLOYEE" ("IDP", "NOM") ENABLE;
